### ISSUE TITLE
support RandomForestClassifier in RuleFitClassifier?

### ISSUE THREAD

**Issue by JSONG006** [csinva/imodels#111]

**Comment by csinva** [comment]
Hi @JSONG006, thanks for your interest in this package :)

I've just added support for RandomForestClassifier in RuleFitClassifier ([here](https://github.com/csinva/imodels/commit/b99f230b0b0aae19e0f7d4d1db713fd976c7f6f3)]). Will be included in the next release!

Best,
Chandan
