### ISSUE TITLE
Bug in Readme: Hierarchical Shrinkage Doesn't Support HistGradientBoostingRegressor

### ISSUE THREAD

**Issue by bridgream** [csinva/imodels#137]
The readme page claims that hierarchical shrinkage supports any sklearn tree-based model, but in reality it only works with sklearn.ensemble.GradientBoostingRegressor and sklearn.ensemble.GradientBoostingClassifier. When used with sklearn.ensemble.HistGradientBoostingRegressor, the _shrink method is nullified because neither of the two conditions is true:
https://github.com/csinva/imodels/blob/master/imodels/tree/hierarchical_shrinkage.py#L125-L127 . This is same for HistGradientBoostingClassifier. 

We should either add support to hist boosting trees, or clarify this in the readme.

**Comment by csinva** [comment]
Thanks for pointing this out! I've just updated this in the readme and we'll try and support `HistGradientBoostingRegressor` soon!
