### ISSUE TITLE
Missing import in README

### ISSUE THREAD

**Issue by davidefiocco** [csinva/imodels#144]
In the README file example use of the library, the model used is a `HSTreeRegressorCV` and that requires an import in https://github.com/csinva/imodels/blob/a86d13bbd695376b65a415d56abe753ecbfa034b/readme.md?plain=1#L31

so that it can be used in 

https://github.com/csinva/imodels/blob/a86d13bbd695376b65a415d56abe753ecbfa034b/readme.md?plain=1#L39

That should be fixed in https://github.com/csinva/imodels/pull/143.

**Comment by csinva** [comment]
Thanks for this fix!
