### ISSUE TITLE
'BoostedRulesClassifier' object has no attribute 'complexity_'

### ISSUE THREAD

**Issue by yinweisu** [csinva/imodels#147]
After imodel being updated to 1.3.8, we've got the error msg `'BoostedRulesClassifier' object has no attribute 'complexity_'`. Wonder is it removed or renamed? It is generally better to keep public apis/attributes unchanged during minor releases, any plan to add it back?

**Comment by csinva** [comment]
Sorry about that! This was a mistake -- will add it back and rebump the version today.

**Comment by csinva** [comment]
Just fixed and bumped the version -- let me know if the error is still present!

**Comment by yinweisu** [comment]
So I tried 1.3.9 and we have another problem:
`AttributeError: 'BoostedRulesClassifier' object has no attribute 'estimator'`

**Comment by csinva** [comment]
Sorry about that, seemed like estimator wasn't being set for certain sklearn versions...just pushed a fix and bumped to `1.3.10`.

**Comment by yinweisu** [comment]
Is `1.3.10` released in pypi? Can't find it yet

**Comment by csinva** [comment]
Should be there now!
