### ISSUE TITLE
Add max_trees hyperparameter for FIGS?

### ISSUE THREAD

**Issue by mepland** [csinva/imodels#152]
In some cases a user may want to make a FIGS model more interpretable by limiting the number of trees. Adding a `max_trees` hyperparameter to complement the existing `max_rules` would be helpful in shaping the model. `max_trees` could be used to keep the number of trees low for easier human review, and to help prevent stump trees from being created.

Note we would keep `max_rules` as is, limiting the total rules / splits across all trees.

**Comment by csinva** [comment]
Very good idea!

**Comment by mepland** [comment]
I'll work on adding it after https://github.com/csinva/imodels/pull/150 then!
