### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by boltzmann-brain** [csinva/imodels#159]
Hello, great project but I came across a few broken links while exploring it.

1. Under [demo notebooks](https://csinva.io/imodels/#demo-notebooks), the links to  `posthoc.ipynb` and `uncertainty.ipynb` are broken.
2. Under [Support for different tasks](https://csinva.io/imodels/#support-for-different-tasks), the link to DistilledRegressor is broken.

**Comment by csinva** [comment]
Thanks for your interest in the package and pointing out these broken links! Just fixed them :)
