### ISSUE TITLE
SkopeRules output

### ISSUE THREAD

**Issue by ukamath** [csinva/imodels#16]
Hello
Thanks for consolidating the implementations into one nice package. I was running SkopeRules on the diabetes dataset and saw that the results are 
('Insulin > 142.0 and Age > 26.5', (0.8732394366197183, 0.7005649717514124, 1))
('Insulin <= 187.5 and Insulin > 121.0 and Age > 24.5', (0.8862208393458393, 0.6502540183068366, 3))
('Insulin <= 169.75 and Insulin > 168.75', (1.0, 0.5337078651685393, 1))
('Insulin > 121.0 and BMI > 30.300000190734863 and Age <= 27.5', (0.5128579777907656, 0.17596669877528553, 2))
('Glucose <= 167.5 and Insulin > 169.75', (0.38333333333333336, 0.12921348314606743, 1))
('Insulin <= 169.75 and Insulin > 143.0 and Age <= 26.5', (0.6923076923076923, 0.10465116279069768, 1))

Looking at the code, I see that the first two elements after the Rule are precision and recall, what is the third integer?
Thanks
Uday

**Comment by csinva** [comment]
Sorry we'll hide that info going forward...it is basically the number of points in the rule overlapping with other existing rules (used for doing deduplication, but not very informative afterwards).
