### ISSUE TITLE
Importing imodels changes default matplotlib plot size config

### ISSUE THREAD

**Issue by davidefiocco** [csinva/imodels#164]
Executing `import imodels` influences the way matplotlib plots are displayed subsequently.

To reproduce, run

```python
import matplotlib.pyplot as plt
import numpy as np
# import imodels

x = np.arange(0, 10, 0.01)
y = np.sin(x)
plt.plot(x, y)
```

with the import commented and uncommented. Plot size will be (very) different, like below:

![size-comparison](https://user-images.githubusercontent.com/4547987/223385638-5bf6b7a2-5332-4429-8f07-abe96da97fcc.png)

Expected behavior (I think) would be the `import` statement not to affect the appearance of figures. This is a bit annoying as the display size is disproportionately large e.g. when using a Jupyter notebook. I'm on `imodels==1.3.15`.

**Comment by csinva** [comment]
Thanks for catching this! You're right this is bad behavior, just pushed a fix in  dba8ba1 and bumped the `imodels version`
