### ISSUE TITLE
Problem importing functions from module `imodels.importance`

### ISSUE THREAD

**Issue by facusapienza21** [csinva/imodels#185]
Hi! 

I was trying to run some of the examples in the [mdi+ demo](https://github.com/csinva/imodels/blob/master/notebooks/mdi_plus_demo.ipynb) (thanks @tiffanymtang for the reference!), but I notice the imports of the module don't work:
```
from imodels.importance import RandomForestPlusRegressor, RandomForestPlusClassifier, \
    RidgeRegressorPPM, LassoRegressorPPM, IdentityTransformer
from imodels.importance.rf_plus import _fast_r2_score
```
I checked and it seems that the `__init__.py` present in the last release of the package doesn't include the respective includes. This is what is present in the `__init__.py` of the last install:
```
"""
Feature importance methods for black box models
"""

from .representation import TreeTransformer
from .r2f import R2F
```
while the right content should be what is currently in the repository [init file](https://github.com/csinva/imodels/blob/master/imodels/importance/__init__.py). 

I was able to run the example by installing directly from the repository, but I thought it may be worth reporting this since other users may encounter the same issue!

**Comment by tiffanymtang** [comment]
@facusapienza21 Thanks for making note of this! @csinva I'm not sure how you prefer to manage new releases of imodels, but please let me know if there's anything you need from me with the MDI+ additions. Thanks both!

**Comment by csinva** [comment]
Ah thanks both for pointing this out! Just bumped the version that includes the updated init file, so should work smoothly now :)
