### ISSUE TITLE
how to set maximum number of rules and maximum length of rules for rulefit ?

### ISSUE THREAD

**Issue by Sandy4321** [csinva/imodels#2]
how to set maximum number of rules and maximum length of rules for rulefit ?

when I set to max_rules = 4 
I get this
rules
                                                 rule  ... importance
0                                                crim  ...   1.437129
7                                                 dis  ...   2.151996
12                                              lstat  ...   2.533759
11                                              black  ...   0.683094
1                                                  zn  ...   0.307754
9                                                 tax  ...   1.825235
8                                                 rad  ...   2.150141
10                                            ptratio  ...   1.735849
6                                                 age  ...   0.489965
5                                                  rm  ...   1.107437
4                                                 nox  ...   1.251279
3                                                chas  ...   0.213609
2                                               indus  ...   0.032803
13                            rm <= 6.805000066757202  ...   1.701190
17  dis > 1.3727499842643738 & rm <= 6.82150006294...  ...   0.221855
22  lstat <= 9.890000343322754 & dis > 1.372749984...  ...   0.030449
19  rm <= 6.821500062942505 & dis <= 2.00444996356...  ...   0.342680
18  rm > 6.821500062942505 & lstat <= 4.7200000286...  ...   2.445310
21  rm > 6.821500062942505 & lstat <= 4.7200000286...  ...   0.836880
15  dis <= 1.3727499842643738 & rm <= 6.8215000629...  ...   2.641944

[20 rows x 5 columns]

rules.columns
Index(['rule', 'type', 'coef', 'support', 'importance'], dtype='object')

from imodels import RuleFit
import pandas as pd
import numpy as np

# load some data
#boston_data = pd.read_csv("../data/boston.csv", index_col=0)
boston_data = pd.read_csv("boston.csv", index_col=0)
y = boston_data.medv.values
X = boston_data.drop("medv", axis=1)
features = X.columns
X = X.values

# fit a rulefit model
rf = RuleFit(max_rules = 4)
'''
    Parameters
    ----------
        tree_size:      Number of terminal nodes in generated trees. If exp_rand_tree_size=True, 
                        this will be the mean number of terminal nodes.
        sample_fract:   fraction of randomly chosen training observations used to produce each tree. 
                        FP 2004 (Sec. 2)
        max_rules:      approximate total number of rules generated for fitting. Note that actual
                        number of rules will usually be lower than this due to duplicates.
        memory_par:     scale multiplier (shrinkage factor) applied to each new tree when 
                        sequentially induced. FP 2004 (Sec. 2)
        rfmode:         'regress' for regression or 'classify' for binary classification.
        lin_standardise: If True, the linear terms will be standardised as per Friedman Sec 3.2
                        by multiplying the winsorised variable by 0.4/stdev.
        lin_trim_quantile: If lin_standardise is True, this quantile will be used to trim linear 
                        terms before standardisation.
        exp_rand_tree_size: If True, each boosted tree will have a different maximum number of 
                        terminal nodes based on an exponential distribution about tree_size. 
                        (Friedman Sec 3.3)
        model_type:     'r': rules only; 'l': linear terms only; 'rl': both rules and linear terms
        random_state:   Integer to initialise random objects and provide repeatability.
        tree_generator: Optional: this object will be used as provided to generate the rules. 
                        This will override almost all the other properties above. 
                        Must be GradientBoostingRegressor or GradientBoostingClassifier, optional (default=None)
'''
rf.fit(X, y, feature_names=features)

# calculate mse on the training data
preds = rf.predict(X)
print(f'train mse: {np.mean(np.square(preds-y)):0.2f}')

rules = rf.get_rules()

rules = rules[rules.coef != 0].sort_values("support", ascending=False)

# 'rule' is how the feature is constructed
# 'coef' is its weight in the final linear model
# 'support' is how many points it applies to
#rules[['rule', 'coef', 'support']].head().style.background_gradient(cmap='viridis')
rules[['rule', 'coef', 'support']].head()
q=0

**Comment by csinva** [comment]
Sorry for the super long delay and thanks for your interest 😄 ! We have been working to unify all the models into a solid base before dealing with details of individual models. Our newest commit should have fixed this issue, and max_rules should work properly now!
