### ISSUE TITLE
how to limit number of rules and  to limit number of conditions in rules  but get best performance for this constrains 

### ISSUE THREAD

**Issue by Sandy4321** [csinva/imodels#3]
can you help to clarify how to set parameters for SBRL
1
to limit number of rules
2
to limit number of conditions in rules

but get best performance for this constrains   

like done in by use of max_card=2, to set maximum number of rules to 2
https://github.com/fingoldin/pycorels
C = CorelsClassifier(max_card=2, c=0.0, verbosity=["loud", "samples"])

what and how to use from these
model = RuleListClassifier(max_iter=10000, class1label="diabetes", verbose=False)
'''
    Parameters
    ----------
    listlengthprior : int, optional (default=3)
        Prior hyperparameter for expected list length (excluding null rule)

    listwidthprior : int, optional (default=1)
        Prior hyperparameter for expected list width (excluding null rule)
        
    maxcardinality : int, optional (default=2)
        Maximum cardinality of an itemset
        
    minsupport : int, optional (default=10)
        Minimum support (%) of an itemset

    alpha : array_like, shape = [n_classes]
        prior hyperparameter for multinomial pseudocounts

    n_chains : int, optional (default=3)
        Number of MCMC chains for inference

    max_iter : int, optional (default=50000)
        Maximum number of iterations
        
    class1label: str, optional (default="class 1")
        Label or description of what the positive class (with y=1) means
        
    verbose: bool, optional (default=True)
        Verbose output
        
    random_state: int
        Random seed
'''

**Comment by csinva** [comment]
Sorry for the super long delay and thanks for your interest 😄 ! We have been working to unify all the models into a solid base before dealing with details of individual models. 

Bayesian Rule List is a very flexible model and this implementation only allows control over the parameters you listed above. In this case, the listwidth prior is the parameter that you most want to vary (the lower it is, the less rules). Limiting maxcardinality will help you get shorter rules. In either case, the algorithm will try to find the best list based on these hyperparameters!
