### ISSUE TITLE
[JOSS] Guide for installation

### ISSUE THREAD

**Issue by jungtaekkim** [csinva/imodels#43]
Hi authors,

I am reviewing your submission and *imodels* repository.

I am looking into your software, but I cannot find a guide for installing your software.

If you support PyPI installation or installation with *setuptools*, please add some description about these for the future users of your software.

Best,
Jungtaek.

**Comment by csinva** [comment]
HI Jungtaek,

Thanks for taking the time to review the software, it is much appreciated! We currently have q line describing the installation process near the top of the readme: 

"Install with `pip install imodels` (see [here](https://github.com/csinva/imodels/blob/master/docs/troubleshooting.md) for help)."

The package can therefore be installed with PyPI (easiest) or through cloning and running `python setup.py install`.

We will make this clearer in the readme!

Best,
Chandan

**Comment by jungtaekkim** [comment]
@csinva Okay, it would be helpful to other users.
I will open other issues if I need to leave a comment.

Best,
Jungtaek.
