### ISSUE TITLE
No module named 'irf'

### ISSUE THREAD

**Issue by CoteDave** [csinva/imodels#5]
for the IRFClassifier, there seems to have a missing file (irf)

from irf.ensemble import wrf
ModuleNotFoundError: No module named 'irf'

When I look in the source files, this file does not exists.

Thanks!

**Comment by csinva** [comment]
Thanks for trying out the package! Sorry about that - we had accidentally commented this out of the dependencies during testing.

This is currently a dependency which can be installed by running `pip install git+https://github.com/Yu-Group/iterative-Random-Forest` (or rerunning the pip install for the imodels package).

We're currently working on integrating this in more cleanly!
