### ISSUE TITLE
Issue with feature_names in GreedyRuleListClassifier

### ISSUE THREAD

**Issue by pauldebdeep9** [csinva/imodels#52]
when i am putting feature_names= X.columns only the first feature is appearing in the rule list and others are appearing as feat i. unable to fix this and request for your kind support.

 here is the output snippet:
Selected features: Index(['Processor(P99)_Q', 'Opto(F99)_Q', 'Logic(L99)_Am', 'Qualcom',
       'Toshiba', 'ABB', 'Whirlpool', 'Honeywell'],
      dtype='object')
mean 0.6 (30 pts)
if Whirlpool >= 153 then 1.0 (16 pts)
mean 0.143 (14 pts)
if feat 1 >= 16882885 then 1.0 (2 pts)
mean 0.0 (12 pts)

**Comment by csinva** [comment]
Thanks for pointing this out, will take a look and get back to you shortly!

**Comment by keyan3** [comment]
Hi @pauldebdeep9, which algorithm were you using when you got this error? Can you also include a snippet of the code that creates this output? Thanks!

**Comment by pauldebdeep9** [comment]
Hello Folks, 
Here is the snippet of my code:

model = GreedyRuleListClassifier()  # initialize a model

X_train= X_train.iloc[:, :].values
X_test= X_test.iloc[:, :].values

model.fit(X_train, y_train, feature_names= X.columns)   # fit model

preds = model.predict(X_test) # discrete predictions: shape is (n_test, 1)
preds_proba = model.predict_proba(X_test) # 


However, I have solved the issue by adding the following lines:
for i in range(len(model.rules_)):
    if 'col' in model.rules_[i]:
        model.rules_[i]['col']= X.columns[model.rules_[i]['index_col']]
#and then
print(model)

Now the feature names are appearing correctly. 

Thanks a lot for developing this excellent package! 

Best
Debdeep
