### ISSUE TITLE
Add conda-forge package

### ISSUE THREAD

**Issue by candalfigomoro** [csinva/imodels#58]
In addition to the pypi package, please add a conda-forge package (https://conda-forge.org).

You can easily create a boilerplate conda recipe with grayskull (starting from the pypi package): https://github.com/conda-incubator/grayskull

**Comment by csinva** [comment]
Following up, I tried setting this up on conda, but it seems that some of our dependencies (e.g. `mlxtend`) are not currently available on conda, so may be difficult to add this support until those packages are updated.

**Comment by candalfigomoro** [comment]
@csinva 
mlxtend is there: https://anaconda.org/conda-forge/mlxtend
I think the missing one is "corels"
