### ISSUE TITLE
GOSDT unable to print tree 

### ISSUE THREAD

**Issue by ja16005** [csinva/imodels#76]
I am utilizing the OptimalTreeClassifier model from GOSDT as shown in the repository example itself. But unable to print the tree and is throwing an "AttributeError: 'OptimalTreeClassifier' object has no attribute 'classes_' " error as shown 

![Screenshot (211)](https://user-images.githubusercontent.com/20997624/146367348-2fbb0dd0-8d52-44f5-b737-07e0ec1bbcb6.png)
But this is throwing a error internally
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_33/809247974.py in <module>
----> 1 test_classification_binary()

/tmp/ipykernel_33/280002779.py in test_classification_binary()
     23         # test acc
     24         acc_train = np.mean(preds == new_y)
---> 25         print(type(m),m, 'final acc', acc_train)
     26         assert acc_train > 0.8, 'acc greater than 0.8'

/opt/conda/lib/python3.7/site-packages/imodels/tree/cart_wrapper.py in __str__(self)
     58             return 'GreedyTree:\n' + export_text(self, feature_names=self.feature_names, show_weights=True)
     59         else:
---> 60             return 'GreedyTree:\n' + export_text(self, show_weights=True)
     61 
     62 

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

/opt/conda/lib/python3.7/site-packages/sklearn/tree/_export.py in export_text(decision_tree, feature_names, max_depth, spacing, decimals, show_weights)
    872     tree_ = decision_tree.tree_
    873     if is_classifier(decision_tree):
--> 874         class_names = decision_tree.classes_
    875     right_child_fmt = "{} {} <= {}\n"
    876     left_child_fmt = "{} {} >  {}\n"

AttributeError: 'OptimalTreeClassifier' object has no attribute 'classes_'
`

**Comment by csinva** [comment]
Hello! Thanks for bringing this to attention - indeed this is a strange issue; we'll get to fixing it.

In the meantime, you should be able to avoid this issue by installing the gosdt dependency (`pip install gosdt`) and then re-running.

**Comment by csinva** [comment]
This should be fixed now!
