### ISSUE TITLE
tree_generator can not support  RuleFitClassifier

### ISSUE THREAD

**Issue by Yannahhh** [csinva/imodels#79]
Hello~ I find when I use the RuleFitClassifier with the parameter tree_generator, there are some problems:

In your [document](https://github.com/csinva/imodels/blob/67e7a2ae9474cd35061b481a70118ef661908608/imodels/rule_set/rule_fit.py), you have mentioned that the value Must be **GradientBoostingRegressor** or **GradientBoostingClassifier**.

But when I am doing it, it has errors to remind me to use **RandomForest and BoostingRegressor**.

I want to confirm whether the tree_generote can not support the classifier???  Or is my wrong to use it, can you give an example about how to do so? Thanks!!

My errors:
![image](https://user-images.githubusercontent.com/32149104/150154076-e0928a89-adfc-4288-9444-a2523ed236d2.png)

**Comment by csinva** [comment]
Hello 👋  Thanks for your interest in the package!

Sorry we had accidentally set this check to only take in GradientBoostingRegressor / RandomForestRegressor, but it should work just fine with GradientBosstingClassifier. Just removed the check, so if you update the package (`pip install --upgrade imodels`), it should work now!

Thanks,
Chandan
